const BRIEF = {

  meta: {
    date: "Thursday, May 28, 2026",
    eurusd: "1.1637",
    eurusd_direction: "rising",
    eurusd_driver: "The dollar softened as Iran-US peace talks progressed toward a Strait of Hormuz reopening deal, pulling Brent crude below $100 and reducing the energy-driven dollar safe-haven bid; EUR/USD recovered from last week's 1.1599 low as European rate expectations stabilised and the DXY [US dollar index] slid further toward the 97.8 level.",
    eurusd_outlook: "If a confirmed Hormuz deal materialises next week, EUR could push toward 1.17-1.18 as energy inflation relief reduces ECB caution; USD-denominated positions face modest FX headwind but any ceasefire breakdown would quickly reverse this — maintain USD exposure as a hedge against deal failure.",
    eurusd_weekly_change: "+0.3%"
  },

  vitals: {
    fear_greed: { value: 60, last_week: 61, label: "Greed", interpretation: "Sentiment held in greed territory for a second consecutive week at 60, just one point below last week's 61. The S&P 500's eighth straight weekly gain sustains the bullish bid, but the slight pullback from 61 to 60 hints at mild profit-taking as investors await Friday's PCE [Personal Consumption Expenditures — the Fed's preferred inflation gauge] print. At 60, the market is confident but not euphoric — the classical contrarian sell zone begins around 75-80." },
    vix: { value: 17.01, last_week: 17.44, label: "Calm", interpretation: "The VIX [CBOE Volatility Index — a real-time measure of expected 30-day S&P 500 volatility; below 20 = calm] drifted fractionally lower from 17.44 to 17.01, consistent with a market that added modest gains without panic. The sub-18 reading reflects options traders pricing benign near-term risk. Watch for a pop toward 19-20 if Friday's PCE data surprises to the upside and reprices the rate-hike probability curve." },
    put_call: { value: 0.55, last_week: 0.49, label: "Bullish tilt", interpretation: "The equity put/call ratio [number of bearish put options traded vs bullish calls; below 0.6 = bullish positioning] ticked back up from last week's extremely low 0.49 toward a more sustainable 0.55. The prior week's 0.49 reading reflected extreme call-buying after the Nvidia earnings beat; the small mean-reversion this week is healthy — traders are still bullish but less feverishly positioned. Readings at 0.55 remain firmly in bullish tilt territory." }
  },

  regime: {
    title: "Peace Hopes + AI Momentum = Eight-Week Run",
    description: "Markets extended their winning streak to eight consecutive weeks as two parallel narratives reinforced each other: the AI infrastructure bull case continued building on Nvidia's record quarter and Jensen Huang's Computex appearance with TSMC, while Middle East peace optimism dragged Brent crude below $100 for the first time since the Iran conflict escalated. Kevin Warsh's formal swearing-in as Fed chair — with markets pricing virtually zero probability of a rate cut this year — adds a hawkish policy overlay, but equity bulls are choosing to focus on earnings rather than rates. The regime strongly favours AI infrastructure, cloud, and travel names while headwinding shipping, energy producers, and EUR-exposed luxury.",
    tailwinds: ["Nvidia Vera Rubin supply commitments locked with TSMC — AI capex cycle confirmed through 2027", "Iran-US peace talks reducing Brent below $100 — inflation relief signal for consumers and central banks", "S&P 500 eighth consecutive weekly gain — institutional momentum strategies remain buyers on dips"],
    headwinds: ["Kevin Warsh as new Fed chair signals zero rate cuts in 2026 — cost of capital stays elevated", "PCE inflation data due Friday May 28 — any upside surprise could break the streak", "EUR/USD only modestly recovering — EUR-based portfolios absorbing FX drag on USD positions"]
  },

  league: {
    winners: [
      { rank: 1, name: "TJX Companies", sector: "Consumer Retail", change: "+9.2%", reason: "Q1 FY2027 blowout: revenue $14.32B and EPS $1.19 both beat; full-year guidance raised; trade-down consumer narrative perfectly validates off-price retail model as value-seeking spending accelerates." },
      { rank: 2, name: "CrowdStrike", sector: "Cybersecurity", change: "+6.1%", reason: "All-time high hit in May as cybersecurity stocks outrun semiconductor peers; ARR [annual contracted subscription revenue] of $4.24B growing 25%+; AI-native security narrative capturing enterprise budget cycles." },
      { rank: 3, name: "AMD", sector: "Semiconductors", change: "+5.4%", reason: "Computex 2026 AI hardware showcase with Lisa Su in Taipei; AI GPU pipeline gaining institutional attention; memory chip supply concern early in week reversed as investors re-rated sector." },
      { rank: 4, name: "Apple", sector: "Consumer Tech", change: "+3.75%", reason: "Fiscal Q2 revenue $111.2B (+17% YoY) and EPS (+22%); all-time high hit at $311.40 on May 22; App Store AI monetisation and services margin expansion driving re-rating to $308.65 end of week." },
      { rank: 5, name: "Tesla", sector: "EV / Autonomous", change: "+3.1%", reason: "Belgium approved Tesla FSD [Full Self-Driving] testing in Flanders region; robotaxi rollout in Texas progressing; stock +60% from 52-week low on autonomous milestone catalysts accumulating." },
      { rank: 6, name: "TSMC", sector: "Semiconductors / Packaging", change: "+2.8%", reason: "Jensen Huang flew to TSMC headquarters to lock Vera Rubin production commitments; CoWoS [Chip-on-Wafer-on-Substrate] capacity sold out through 2026; Kumamoto fab upgrade to 3nm confirmed." },
      { rank: 7, name: "Broadcom", sector: "Semiconductors", change: "+2.5%", reason: "Custom AI ASIC [application-specific integrated circuit] demand from hyperscalers driving backlog [signed contracts not yet fulfilled] growth; custom silicon growing at 44.6% CAGR." },
      { rank: 8, name: "ServiceNow", sector: "Enterprise SaaS", change: "+2.4%", reason: "BofA reiterated positive stance; AI-centric Knowledge 2026 event catalyst; enterprise workflow automation gaining fresh institutional flows after 39% YTD drawdown bottomed in April." },
      { rank: 9, name: "Alphabet", sector: "Cloud / AI / Ads", change: "+2.1%", reason: "Google Cloud Q1 +63% YoY momentum sustains; Ironwood TPU deployment exceeding one million units for Anthropic; Search AI Overviews monetisation tracking above internal expectations." },
      { rank: 10, name: "Palantir", sector: "AI / Government Tech", change: "+1.8%", reason: "Stock held near $134-135; DHS $1B AI contract and USDA $300M modernisation deal underpin commercial and government pipeline; US commercial ARR up 133% YoY." },
      { rank: 11, name: "On Holding", sector: "Athletic Consumer", change: "+1.7%", reason: "Premium athletic footwear resilient in trade-down environment; direct-to-consumer mix improving margins; brand momentum vs. Nike and Adidas continues in running and performance segments." },
      { rank: 12, name: "Walmart", sector: "Consumer Staples", change: "+1.5%", reason: "Trade-down consumer trend accelerating to value retailers; advertising and membership revenue diversifying beyond low-margin grocery; Q1 earnings confirmed sector leadership." },
      { rank: 13, name: "Meta Platforms", sector: "Social Media / AI", change: "+1.4%", reason: "Ad revenue +33% YoY from Q1 sustains; Llama open-source AI model enterprise adoption growing; investor sentiment recovered after initial capex-guidance shock settled." },
      { rank: 14, name: "Progressive", sector: "Insurance", change: "+1.3%", reason: "Auto insurance pricing cycle favourable; combined ratio [claims paid as percentage of premiums — below 100% means profit] improving; rising investment yields boosting float income." },
      { rank: 15, name: "Alibaba", sector: "EM / China Tech", change: "+1.2%", reason: "Cloud revenue grew 38% to $6.04B in Q4 FY2026; AI-related products now 30% of external cloud revenue; ceasefire and de-escalation narrative attracting incremental EM allocation." },
      { rank: 16, name: "Trip.com", sector: "Travel / Asia Tech", change: "+1.1%", reason: "Asia-Pacific intra-regional travel recovery outpacing Western markets; Japan tourism surge from yen weakness; Middle East peace hopes lowering broader geopolitical travel risk premium." },
      { rank: 17, name: "Netflix", sector: "Consumer Tech / Media", change: "+1.0%", reason: "Live sports event strategy expanding; ad-supported tier monetisation accelerating; subscriber retention above expectations globally; AI-personalised content recommendation efficiency improving." },
      { rank: 18, name: "Garmin", sector: "Consumer Tech / Wearables", change: "+0.9%", reason: "Aviation and marine GPS demand robust; smartwatch segment outperforming amid outdoor and fitness trend recovery; recurring software revenue model gaining margin appreciation." },
      { rank: 19, name: "Spotify", sector: "Consumer Tech / Audio", change: "+0.8%", reason: "Podcast monetisation accelerating; premium subscriber stickiness above consensus expectations; ad-supported growth beats; AI-generated playlists driving engagement depth metrics." },
      { rank: 20, name: "Global Ship Lease", sector: "Shipping", change: "+0.7%", reason: "Q1 2026 results: 100% charter coverage for 2026, 86% for 2027, over $2B contracted revenues; Zim Norfolk and Zim Xiamen extensions locked for 60-63 months at strong rates." }
    ],
    losers: [
      { rank: 1, name: "MercadoLibre", sector: "EM / Latin America Tech", change: "-14.0%", reason: "Q1 2026 revenue $8.85B (+49% YoY) but net income fell 16% YoY; credit portfolio provisions rising faster than expected; investors punished growth-at-the-cost-of-profitability trajectory." },
      { rank: 2, name: "Airbnb", sector: "Travel / Leisure", change: "-7.0%", reason: "Insider selling, new debt issuance, and fresh travel demand signals weighed on stock despite Q1 revenue +18% YoY; investors concerned about decelerating nights-booked growth in key markets." },
      { rank: 3, name: "Booking Holdings", sector: "Travel / Leisure", change: "-6.0%", reason: "Bernstein cut price target; stock down 27% YTD despite strong fundamentals; markets questioning travel demand durability as Middle East geopolitics and energy costs weigh on forward booking intent." },
      { rank: 4, name: "International Seaways", sector: "Shipping / Tankers", change: "-5.5%", reason: "Iran peace talks reducing the geopolitical tanker premium; lower expected oil output and potentially reopened Strait of Hormuz removes the route-extension bonus that inflated charter rates." },
      { rank: 5, name: "Tsakos Energy Navigation", sector: "Shipping / Tankers", change: "-4.8%", reason: "Tanker-specific risk premium unwinding as US-Iran negotiations advance; crude oil routing from Middle East normalising could cut voyage revenue per trip materially." },
      { rank: 6, name: "StealthGas", sector: "Shipping / LPG", change: "-4.2%", reason: "LPG [liquefied petroleum gas] charter rate [daily vessel rental price] softening; smaller operators lack pricing power; geopolitical risk premium unwinding from energy shipping names broadly." },
      { rank: 7, name: "Danaos", sector: "Shipping / Container", change: "-3.9%", reason: "Container charter rates under structural pressure; newbuild [newly manufactured vessel] deliveries from 2021-2023 orders arriving into soft demand environment; long-term contract renewals pricing lower." },
      { rank: 8, name: "Novo Nordisk", sector: "Healthcare / Pharma", change: "-3.2%", reason: "Eli Lilly Foundayo oral GLP-1 [glucagon-like peptide — the drug class powering obesity treatment] now in direct US market competition; NVO guiding full-year revenue and profit decline in 2026." },
      { rank: 9, name: "Rheinmetall", sector: "EU Defence", change: "-2.4%", reason: "Iran ceasefire progress reduces near-term defence urgency premium; stock volatile around EUR 1,247 after JPMorgan downgrade; still down ~25% YTD despite long-term EU rearmament thesis intact." },
      { rank: 10, name: "UnitedHealth", sector: "Healthcare / Managed Care", change: "-1.8%", reason: "Berkshire Hathaway exited its position entirely in Q1 2026 under Greg Abel; DOJ probe ongoing; stock down ~55% from all-time high at ~$280; managed-care sector uncertainty persists." },
      { rank: 11, name: "Starbucks", sector: "Consumer", change: "-1.6%", reason: "Consumer confidence at historic lows driving trade-down away from premium coffee; store traffic declining in US; turnaround under new CEO taking materially longer than investor expectations." },
      { rank: 12, name: "LVMH", sector: "Luxury", change: "-1.4%", reason: "Softening Chinese luxury demand remains structural headwind; EUR weakness compressing euro-reported revenues on USD-denominated global sales; European consumer energy inflation reducing discretionary spend." },
      { rank: 13, name: "Chewy", sector: "Consumer E-Commerce", change: "-1.2%", reason: "Pet discretionary spending softening; subscription model dampening but not fully offsetting macro headwind; path to GAAP [standard accounting profit] profitability extended beyond prior guidance." },
      { rank: 14, name: "Intel", sector: "Semiconductors", change: "-1.1%", reason: "Continues losing foundry and data center share; no credible AI revenue catalyst; Lip-Bu Tan restructuring still in early stages; Computex 2026 keynote lacked high-conviction product announcements." },
      { rank: 15, name: "Celsius Holdings", sector: "Consumer Beverages", change: "-1.0%", reason: "Energy drink category competition intensifying; PepsiCo distribution partnership volume ramp slower than expected; premium positioning tested by consumer trade-down pressures." },
      { rank: 16, name: "Grab", sector: "EM / Southeast Asia", change: "-0.9%", reason: "Geopolitical risk premium weighing on Southeast Asian platforms; energy price inflation compressing delivery unit economics; dollar flows moving to US equities over EM allocations." },
      { rank: 17, name: "DoorDash", sector: "Consumer Tech", change: "-0.8%", reason: "Food delivery margin under pressure from wage inflation; average order values declining as consumers trade down; GAAP profitability timeline pushed further out than bulls projected." },
      { rank: 18, name: "FinVolution", sector: "EM / China Fintech", change: "-0.7%", reason: "China consumer credit demand soft; ADR [American Depositary Receipt — a US-listed foreign company share] valuation compressed by USD strength; cross-border fintech regulatory uncertainty ongoing." },
      { rank: 19, name: "Ulta Beauty", sector: "Consumer", change: "-0.7%", reason: "Beauty discretionary spending softening as consumers trade down; Amazon beauty category acceleration intensifying competitive pressure; promotional pricing required to maintain store traffic." },
      { rank: 20, name: "Hello Group", sector: "EM / China Social", change: "-0.5%", reason: "China social media monetisation under regulatory scrutiny; mature market user growth plateauing; USD strength compressing ADR valuations; no near-term catalyst to reverse institutional outflows." }
    ]
  },

  sectors: [
    { name: "US Technology", change: "+0.9%", direction: "up", driver: "Computex 2026 AI hardware announcements from Nvidia (Vera Rubin) and AMD sustained tech sentiment; memory chip capacity concern mid-week was absorbed by the broader AI bullishness." },
    { name: "US Semiconductors", change: "+1.8%", direction: "up", driver: "Nvidia-TSMC Vera Rubin supply commitments locked; Micron HBM4 production for Vera Rubin confirmed; TSMC CoWoS capacity sold out through 2026 signals sustained revenue visibility." },
    { name: "US Healthcare", change: "-0.6%", direction: "down", driver: "UnitedHealth continued rebound stalled; Novo Nordisk GLP-1 competition weighing on managed care and pharma names simultaneously; healthcare sector down 9.7% YTD still a structural drag." },
    { name: "US Financials", change: "+0.8%", direction: "up", driver: "Kevin Warsh sworn in as new Fed chair — hawkish lean supports bank NIM [net interest margin — spread between loan income and deposit costs]; Progressive and Interactive Brokers showing strength." },
    { name: "US Industrials", change: "+1.2%", direction: "up", driver: "HEICO, Howmet Aerospace, Comfort Systems benefiting from sustained defence and construction demand; Dow Jones industrial average hit fresh record close this week." },
    { name: "US Energy", change: "-1.5%", direction: "down", driver: "Iran-US peace negotiations pushed Brent crude below $100 for first time in months; tanker and refinery margin compression on lower forward oil price expectations." },
    { name: "US Consumer Discretionary", change: "+1.0%", direction: "up", driver: "TJX +9% on blowout earnings led the sector; Tesla +3% on FSD expansion news; partially offset by travel names (Airbnb -7%, Booking -6%) on valuation concerns." },
    { name: "US Consumer Staples", change: "+1.5%", direction: "up", driver: "Walmart continued to benefit from trade-down trend; TJX blowout earnings extended the value-retail narrative; defensive positioning ahead of Friday PCE data attracted flows." },
    { name: "US Real Estate", change: "+0.5%", direction: "up", driver: "10-year Treasury yield stabilised; data center REITs benefiting from AI infrastructure demand; residential REITs cautious on rates-higher-for-longer under Warsh." },
    { name: "US Utilities", change: "-0.7%", direction: "down", driver: "Rising inflation expectations and Warsh hawkish posture reduce rate-cut expectations, compressing utility dividend valuations; energy utilities hit by oil price decline." },
    { name: "US Comm Services", change: "+0.8%", direction: "up", driver: "Netflix and Spotify gains; Meta sustained ad revenue momentum; Alphabet cloud strength; sector recovering from -5.5% Q1 drag with fresh institutional flows." },
    { name: "EU Defence", change: "-1.5%", direction: "down", driver: "Iran ceasefire progress reducing near-term defence urgency premium; Rheinmetall volatile around EUR 1,247; EU rearmament structural thesis intact but near-term catalyst lacking." },
    { name: "EU Banks", change: "+1.0%", direction: "up", driver: "Santander, BNP Paribas gaining on stable ECB rate expectations; European bank NIM improving with rates on hold longer than markets priced 6 months ago." },
    { name: "EU Industrials", change: "+1.3%", direction: "up", driver: "Siemens and Heidelberg Materials benefiting from infrastructure and construction demand; Dow Jones European industrials tracking US sector optimism." },
    { name: "EU Luxury", change: "-1.1%", direction: "down", driver: "LVMH and sector under pressure from softening China demand and EUR weakness; no near-term catalyst visible for Chinese luxury recovery heading into summer." },
    { name: "EU Autos", change: "+0.5%", direction: "up", driver: "Toyota hybrid demand robust; EV transition concerns slightly easing on China EV import tariff truce discussions; modest sector recovery from prior-week lows." },
    { name: "EU Insurance", change: "+0.7%", direction: "up", driver: "Allianz and Munich Re benefiting from elevated premium rates and improving investment yields; catastrophe loss environment normalising from 2025 highs." }
  ],

  flows: [
    { label: "US Equities", amount: "+$13.4B", direction: "in", pct: 62, note: "Ninth consecutive week of net inflows as the S&P 500 eight-week winning streak attracted momentum-chasing institutional and retail flows; tech and consumer staples led sector allocations." },
    { label: "European Equities", amount: "+$8.1B", direction: "in", pct: 58, note: "BofA flagged 2026 as a new world order for international stocks — $104B has rotated to developed international equities YTD vs only $25B to US equities; EU defence rearmament mega-trend attracting fresh capital." },
    { label: "EM Equities", amount: "-$3.2B", direction: "out", pct: 38, note: "MercadoLibre earnings shock (-14% on the week) and China macro uncertainty drove outflows; dollar strength remains a structural headwind for EM equity allocation decisions globally." },
    { label: "Gold & Commodities", amount: "+$2.6B", direction: "in", pct: 55, note: "Gold held above $4,700/oz despite mild dollar recovery; inflation hedge demand sustaining flows; oil commodity fund outflows partially offset gold inflows." },
    { label: "Fixed Income", amount: "+$12.6B", direction: "in", pct: 60, note: "Bond fund inflows sustained as yield levels remain attractive; taxable bond funds seeing $10.7B weekly inflows as investors build duration ahead of any eventual Fed pivot." },
    { label: "Cash / Money Markets", amount: "+$6.5B", direction: "in", pct: 50, note: "Money market funds attracting steady flows given zero probability of rate cuts in 2026; investors maintaining tactical cash to deploy opportunistically on any PCE-driven equity dip." }
  ],

  trends: [
    { num: "01", title: "AI infrastructure entering the physical world", detail: "Nvidia's Jensen Huang flew to TSMC headquarters this week to lock in production commitments for the Vera Rubin platform, described as the largest product launch in Taiwan's history delivering 3.5x training and 5x inference performance vs Blackwell. CoWoS packaging capacity is sold out through 2026 and TSMC is scaling from 35,000 to 130,000 wafers/month. The AI trade is physically manifesting in supply chain constraints, fab construction, and record hyperscaler capex commitments totalling over $700B for 2026.", status: "CONFIRMED", evidence: "Jensen Huang confirmed Vera Rubin entered full production at TSMC; Nvidia Q1 FY27 data center revenue $75.2B (+92% YoY); CoWoS capacity sold out through 2026.", type: "structural" },
    { num: "02", title: "Europe's strategic autonomy moment", detail: "EU rearmament spending reached EUR 864B in 2025, 14% above 2024 levels, with NATO members committed to 3.5% GDP defence spending by 2035. The sector faces near-term profit-taking as Iran ceasefire reduces urgency premium, but the structural order cycle running through 2030+ is unaffected. TSMC Kumamoto fab upgrade to 3nm signals Europe and Asia building semiconductor sovereignty, though Europe's own chip independence remains underfunded relative to the US CHIPS Act.", status: "CONFIRMED", evidence: "Global military spending hit record $2.89T in 2025; EU rearmament plan EUR 400B ahead of schedule; TSMC Kumamoto confirmed 3nm upgrade with Sony JV.", type: "structural" },
    { num: "03", title: "Dollar hegemony softening", detail: "The DXY has fallen ~14% from its 2022 peak to around 97.8, with global central banks net selling $48B in dollar reserves in January alone and the dollar's share of global reserves falling to 58.2%, a new low since 1995. BRICS nations raised local-currency trade settlement from 35% to 50%; Iran is charging yuan-denominated tolls at the Strait of Hormuz. The EUR/USD recovery toward 1.1637 this week and continued dollar outflows suggest the structural dollar weakening thesis is on track.", status: "CONFIRMED", evidence: "DXY near 97.8; every major bank forecasting softer dollar by Q4 2026; BRICS local-currency trade share rising to 50%; USD reserve share at 58.2% new low.", type: "structural" },
    { num: "04", title: "GLP-1 drugs reshaping healthcare economics", detail: "Oral GLP-1 pills became the dominant narrative this week as Eli Lilly's Foundayo launched directly into Novo Nordisk's Wegovy market. Novo's oral pill is growing double-digits despite competition and holds 65% of new US prescriptions, but the company is guiding a full-year revenue and profit decline in 2026. The economics are shifting from injectable duopoly to multi-player oral pill competition, compressing margins industry-wide while expanding total market size. UnitedHealth's ongoing managed-care crisis and DOJ probe adds a downstream payer-side disruption layer.", status: "MIXED", evidence: "Novo Nordisk guiding full-year revenue and profit decline; Eli Lilly Foundayo launched in direct US competition; oral GLP-1 market now multi-player.", type: "structural" },
    { num: "05", title: "Trade fragmentation creating shipping opportunities", detail: "China's share of US container imports has dropped from 40% to under 29% as tariffs redirect supply chains through Southeast Asia. Container charter rates face structural pressure from a newbuild oversupply cycle while tanker rates are under pressure from Iran peace talks. The fragmentation creates a bifurcated opportunity: containerships are oversupplied and repricing lower, while specialised tankers serving the new indirect routing networks through India and Southeast Asian corridors remain a medium-term opportunity.", status: "WEAKENED", evidence: "Tanker rates fell on Iran peace hopes; container overcapacity persisting from 2021-2023 newbuild cycle; both major shipping sub-sectors headwinded simultaneously.", type: "cyclical" },
    { num: "06", title: "Retail cash rotation to equities building", detail: "The S&P 500 is in its eighth consecutive winning week, its longest streak since 2023, with retail participation running near 20% of average daily trading volume. JPMorgan data showed retail inflows up 60% YoY in 2025, and the pattern is sustaining into 2026. Money market funds still attract flows but the marginal dollar is increasingly going to equities as the winning streak builds FOMO [fear of missing out] among cash holders.", status: "CONFIRMED", evidence: "S&P 500 8th straight weekly gain — longest since 2023; retail trading at ~20% of average daily volume; equity fund inflows ninth consecutive positive week.", type: "cyclical" }
  ],

  executive: {
    biggest_mover: { name: "TJX Companies", change: "+9.2%", reason: "TJX delivered a blowout Q1 FY2027 with $14.32B revenue and $1.19 EPS both above consensus, and management raised its full-year guidance — the exact playbook for stocks with strong fundamental momentum. The move confirmed that the trade-down consumer thesis [consumers moving from premium to value retail amid inflation pressure] is accelerating, not plateauing, and positions TJX as one of the clearest beneficiaries of persistent consumer-cost stress heading into summer." },
    key_risk: { name: "Friday PCE Inflation Print (May 28)", reason: "The Bureau of Economic Analysis releases PCE [Personal Consumption Expenditures — the Federal Reserve's preferred inflation measure] alongside the GDP second estimate on Friday, with core PCE already running at 3.2% annual — well above the Fed's 2% target. A hot print would reprice the already-thin probability of any 2026 rate cuts to essentially zero and potentially push the September rate-hike probability above 10%, which would snap the eight-week winning streak and pressure Mag7 multiples immediately." },
    conviction_call: { name: "TSMC (TSM)", observation: "TSMC sits at the intersection of every structural theme that is working: Jensen Huang flew to Hsinchu to lock Vera Rubin supply commitments, the Kumamoto fab upgrade to 3nm is confirmed, CoWoS [advanced chip packaging] is sold out through 2026, and the Sony Semiconductor joint venture in Kumamoto adds another revenue stream. At ~24x forward earnings vs Broadcom at ~38x, TSMC is the cheapest way to own the AI infrastructure build-out with the most defensible moat — it is the only company that can physically produce what the AI era demands." },
    macro_pulse: { name: "Kevin Warsh Sworn In as Fed Chair", observation: "Kevin Warsh took the oath of office in a White House ceremony — the first Fed swearing-in at the White House since Greenspan in 1987 — marking the most divisive Fed confirmation in history at 54-45. Markets are pricing less than 3% probability of any rate cut at remaining 2026 FOMC meetings, with some desks raising September rate-hike odds above 5%; Warsh inherits core PCE at 3.2%, shelter inflation doubling in April, and Brent crude only just below $100 — a genuinely hostile inflation environment." },
    tags: [
      { label: "EUR/USD: 1.1637 rising", type: "green" },
      { label: "Fed: 0% cut probability 2026", type: "red" },
      { label: "ECB: on hold — watching PCE", type: "amber" },
      { label: "Tariffs: 25% semi import levy active", type: "amber" },
      { label: "AI capex: $700B+ from Mag4 in 2026", type: "green" },
      { label: "EU defence: -1.5% week, LT intact", type: "amber" },
      { label: "Semis: Vera Rubin production locked", type: "green" },
      { label: "Shipping: tanker rates falling on peace deal", type: "red" }
    ]
  },

  macro: {
    us: "The US economy heads into the last week of May with inflation above 3% on the core PCE measure, a new Federal Reserve chair in Kevin Warsh who inherited a committee in no mood to cut rates, and an equity market that has nonetheless posted eight consecutive weekly gains. The dominant story is the divergence between strong corporate earnings — particularly from AI-exposed names — and a monetary policy backdrop that is tighter than at any point since the inflation surge began. Fed minutes from Jerome Powell's last FOMC meeting revealed the committee was openly discussing rate hikes if necessary. Consumer confidence remains near historic lows even as the equity market hits records, a disconnect reflecting the bifurcation between asset-owning households (booming) and wage-dependent households (squeezed by energy and food inflation). PCE data on Friday May 28 is the week's key data release; a hot print would be the first real test of Warsh's resolve and equity market resilience.",
    europe: "Europe is caught between structural optimism and cyclical headwinds. The EU rearmament programme is running ahead of schedule at EUR 400B spent in 2025 alone with NATO members committed to 3.5% GDP defence spending by 2035, but the near-term catalyst for defence stocks is fading as Iran-US peace talks progress. The ECB is watching the US PCE print closely because any US rate hike signal will constrain the ECB's room to ease even as European growth slows. The EUR/USD recovery from last week's 1.1599 to 1.1637 provides mild relief for EUR-based portfolios holding USD assets, but structural dollar weakness and energy-inflation headwinds mean European consumers and central bankers face a difficult second half. TSMC's Kumamoto upgrade to 3nm and the Sony Semiconductor joint venture signal that Japan and Europe are meaningfully investing in technology sovereignty, partially offsetting dependence on US and Taiwanese supply chains.",
    asia: "Japan remains a semiconductor bright spot — TSMC Kumamoto upgrading from 7nm to 3nm is a strategic inflection, and the Bank of Japan's cautious-hold at 0.75% with a possible June hike keeps the JPY carry trade [investors borrowing cheap yen to buy global assets] moderately intact, though a surprise BOJ hike at June meeting would trigger rapid carry unwind across global tech names. Korea's SK Hynix dominates HBM [high-bandwidth memory] with 62% share and revenue up 198% YoY; Samsung is racing to qualify HBM4 for Nvidia Vera Rubin but is currently allocated only 30% of first-wave contracts per SemiAnalysis estimates. China's SMIC is testing a domestic immersion DUV [deep ultraviolet lithography] machine — the first credible step toward domestic lithography self-sufficiency, though volume production remains years away. The Middle East ceasefire impact on Asian shipping routes will be closely watched next week.",
    forward: "The key event next week is Friday May 28's PCE inflation and GDP second-estimate release — this is the most important US data point of the month and will either validate or challenge the rate-hike narrative. Also watch: Costco and Dell earnings Thursday May 28 for consumer and enterprise spending signals; Marvell and Salesforce on Wednesday for AI enterprise software demand confirmation; and the Computex 2026 formal programme opening June 1 with Jensen Huang's GTC Taipei keynote expected to officially unveil Vera Rubin platform details and announce new AI factory partnership deals. On macro policy, the BOJ's summary of opinions from the April meeting flagged possible June rate action — any hint of imminent hike will pressure JPY carry positions and hit Tokyo Electron and other Japan tech names hard within hours."
  },

  mag7: [
    { name: "Apple", ticker: "AAPL", price: "$308.65", change: "+3.75%", pe: "~31x", pe_plain: "paying 31 years of annual earnings", target: "$285-350", theme: "Services flywheel + AI monetisation", news: "Apple hit an all-time high of $311.40 on May 22 before closing the week at $308.65, up 3.75%. Fiscal Q2 revenue of $111.2B came in 17% higher year-on-year with EPS up 22%, powered by the App Store, Apple Intelligence integration in iPhones, and accelerating services margin. The company is up 57% over the past year, cementing its position as the leading consumer AI monetisation story in the Mag7.", earnings: "July 2026 (est)", earnings_proximity: "upcoming", verdict: "HOLD", verdict_reason: "Exceptional execution but trading near all-time highs at 31x forward earnings — wait for a 5-7% pullback to add before the next earnings catalyst." },
    { name: "Microsoft", ticker: "MSFT", price: "$418.57", change: "-0.5%", pe: "~30x", pe_plain: "paying 30 years of annual earnings", target: "$430-500", theme: "Azure AI at $37B ARR — fastest-growing cloud unit", news: "Microsoft's Azure AI annual revenue run rate crossed $37 billion — up 123% — in Q3 FY2026, with the full Intelligent Cloud segment at $34.68B. Despite beating on all metrics with $82.9B quarterly revenue (+18%), the stock remains down 12% YTD as management guided $190B in FY26 capex (+61%). Warsh's hawkish arrival reduces the appeal of high-capex growth stories near-term.", earnings: "July 2026 (est)", earnings_proximity: "upcoming", verdict: "BUY", verdict_reason: "Azure AI at $37B ARR growing 123% is fundamentally undervalued at 30x forward earnings given the earnings acceleration trajectory once capex peaks." },
    { name: "Amazon", ticker: "AMZN", price: "$264.65", change: "+0.5%", pe: "~32x", pe_plain: "paying 32 years of annual earnings", target: "$260-310", theme: "AWS AI infrastructure — $200B capex commitment", news: "AWS revenue grew 22% to $27.8B in Q1 2026 and Amazon is committing $200 billion to AI infrastructure through 2026-2027 while a Snowflake multi-year partnership was announced May 27. The $16.8B accounting windfall from the Anthropic investment boosted Q1 net profit significantly. UBS flagged significant AI contracts with Anthropic and OpenAI as underpinning AWS revenue projections through 2027.", earnings: "July 2026 (est)", earnings_proximity: "upcoming", verdict: "BUY", verdict_reason: "AWS growing 22% with $200B AI infrastructure commitment and Bedrock/Anthropic ecosystem traction — the cloud AI monetisation story is strongest here." },
    { name: "Alphabet", ticker: "GOOGL", price: "$389.50", change: "+2.1%", pe: "~22x", pe_plain: "paying 22 years of annual earnings", target: "$390-460", theme: "Google Cloud +63% YoY — cheapest Mag7 valuation", news: "Alphabet reported Q1 revenue of $109.9B versus $107.2B expected; Google Cloud crossed $20 billion in quarterly revenue for the first time, growing 63% year-on-year. The company updated its full-year capex guidance to as much as $190 billion and has deployed over one million Google Ironwood TPU [tensor processing unit — Google's custom AI chip] chips for Anthropic inference workloads.", earnings: "July 2026 (est)", earnings_proximity: "upcoming", verdict: "BUY", verdict_reason: "Cheapest Mag7 at ~22x forward earnings with Cloud growing 63% — the valuation discount to peers is unjustified given the fundamental AI revenue acceleration." },
    { name: "Meta", ticker: "META", price: "$612.34", change: "+1.4%", pe: "~25x", pe_plain: "paying 25 years of annual earnings", target: "$580-700", theme: "Ad revenue +33% — funding $145B AI bet", news: "Meta raised its 2026 AI spending forecast to $125-145 billion, up from $115-135B. Q1 revenue grew 33% to $56.31B with adjusted EPS of $7.31 beating estimates by $0.52. When Zuckerberg was asked about ROI from the $145B AI spend, he called the question very technical — a phrase that caused initial post-earnings selling before fundamentals reasserted.", earnings: "October 2026 (est)", earnings_proximity: "far", verdict: "HOLD", verdict_reason: "Exceptional ad revenue growth but the $145B capex spend with unclear near-term ROI creates a binary risk — hold existing positions but new capital waits for ROI evidence." },
    { name: "Nvidia", ticker: "NVDA", price: "$213.95", change: "-1.8%", pe: "~24x", pe_plain: "paying 24 years of annual earnings", target: "$272-300", theme: "Vera Rubin — next-gen AI platform entering production", news: "Despite posting record $81.6B revenue (+85% YoY) and guiding $91B for Q2 FY27, Nvidia shares dipped slightly as the stock had rallied 13.7% heading into earnings in a classic buy-the-rumour-sell-the-news pattern. Jensen Huang flew to TSMC this week for Computex 2026 to lock Vera Rubin production commitments — the platform delivers 3.5x training performance vs Blackwell with production already ramping.", earnings: "August 2026 (est)", earnings_proximity: "upcoming", verdict: "BUY", verdict_reason: "Vera Rubin production locked, $91B Q2 guide, and data center revenue at 92% growth — the slight post-earnings dip is the buy-the-dip opportunity the market has been waiting for." },
    { name: "Tesla", ticker: "TSLA", price: "$440.21", change: "+3.1%", pe: "~60x", pe_plain: "paying 60 years of annual earnings", target: "$380-498", theme: "Robotaxi + FSD global expansion", news: "Tesla received approval to test its Full Self-Driving software in Belgium's Flanders region, adding to an expanding global FSD footprint. Texas robotaxi rollout is encountering early challenges but progressing. China April EV sales were +36% YoY. The stock trades near the top of its 52-week range at $440, up dramatically from the $273 52-week low, on accumulated autonomous vehicle milestone catalysts.", earnings: "July 2026 (est)", earnings_proximity: "upcoming", verdict: "WATCH", verdict_reason: "Autonomous milestones accumulating globally but at 60x forward earnings the stock prices a perfect robotaxi execution — watch for any regulatory setback or Texas rollout problem before adding." }
  ],

  theses: [
    { num: "01", title: "AI Infrastructure Entering the Physical World", status: "CONFIRMED", evidence: "Jensen Huang confirmed Vera Rubin production at TSMC this week; CoWoS packaging sold out through 2026 — the AI buildout has now physically saturated advanced semiconductor supply chains.", instruments: "Nvidia, TSMC, AMD, Broadcom, SK Hynix, Micron, Pure Storage, ServiceNow, Palantir",
      highlights: [
        { name: "Nvidia", change: "-1.8%", note: "Post-earnings sell-the-news dip after $81.6B record Q1 revenue; $91B Q2 guide and Vera Rubin production lock confirm the structural thesis is fully intact — the dip is a buying opportunity." },
        { name: "TSMC", change: "+2.8%", note: "Jensen Huang site visit to lock Vera Rubin supply commitments; Kumamoto 3nm upgrade confirmed; CoWoS [advanced chip packaging] demand exceeds all prior capacity forecasts through 2026." },
        { name: "Broadcom", change: "+2.5%", note: "Custom AI ASIC [application-specific integrated circuit] business growing at 44.6% CAGR; hyperscaler customers deepening dependence on Broadcom custom silicon for both inference and training workloads." },
        { name: "Palantir", change: "+1.8%", note: "US commercial ARR [annual contracted subscription revenue] grew 133% YoY; government AI contract pipeline (DHS $1B, USDA $300M) provides durable revenue base as commercial pipeline scales." }
      ]
    },
    { num: "02", title: "Europe's Strategic Autonomy Moment", status: "UNCHANGED", evidence: "EU rearmament on track at EUR 864B in 2025, 14% above prior year; NATO 3.5% GDP target locked; near-term Iran ceasefire reduces defence urgency premium but structural order cycle is 10-year duration.", instruments: "Rheinmetall, Safran, Thales, ASML, VanEck Defense ETF",
      highlights: [
        { name: "Rheinmetall", change: "-2.4%", note: "Short-term profit-taking on Iran ceasefire optimism; stock volatile around EUR 1,247 after JPMorgan downgrade but long-term order book running through 2030 is unaffected by near-term de-escalation." },
        { name: "ASML", change: "+0.5%", note: "EUV [extreme ultraviolet lithography — the only technology producing sub-7nm chips at volume] monopoly intact; SMIC testing domestic DUV but still at 28nm — ASML's monopoly premium is secure for 3-5 years." },
        { name: "Safran", change: "+0.8%", note: "Civil and defence revenue balance insulates from pure-play defence volatility; LEAP engine programme sustaining aerospace revenue regardless of defence news flow near-term." },
        { name: "VanEck Defense ETF", change: "-1.2%", note: "Iran peace deal progress dragged defence ETF lower on reduced urgency premium; structural 10-year NATO spending commitment means this is a tactical correction, not a trend reversal." }
      ]
    },
    { num: "03", title: "Dollar Hegemony Softening", status: "CONFIRMED", evidence: "DXY at 97.8 — down 14% from 2022 peak; global central banks net sold $48B in dollar reserves in January; dollar's share of global reserves fell to 58.2% — new low since 1995.", instruments: "iShares MSCI Europe, iShares ACWI, VanEck Rare Earth, iShares Physical Gold, WisdomTree Bitcoin",
      highlights: [
        { name: "Gold (iShares Physical Gold)", change: "+0.8%", note: "Gold holding above $4,700/oz; up 65% year-on-year from January's $5,595 all-time high; dollar weakness and inflation hedge demand sustaining structural ETF inflows." },
        { name: "iShares MSCI Europe", change: "+1.9%", note: "European equity outperformance continues — $104B has rotated to developed international equities YTD vs only $25B to US equities; structural dollar-diversification thesis driving flows." },
        { name: "WisdomTree Bitcoin ETP", change: "+1.5%", note: "Bitcoin hovering near $68-70k after retracing from $122k all-time high; dollar weakness narrative sustains crypto as a non-dollar reserve alternative among institutional allocators." },
        { name: "WisdomTree Ethereum ETP", change: "+0.8%", note: "Ethereum above $2,000; institutional momentum and regulatory optimism in 2026 sustaining gradual allocation increase; dollar softening provides macro tailwind for non-USD assets." }
      ]
    },
    { num: "04", title: "GLP-1 Drugs Reshaping Healthcare Economics", status: "MIXED", evidence: "Novo Nordisk Wegovy oral pill doubled sales estimates but full-year guidance was cut; Eli Lilly Foundayo launched directly into US competition — the market is expanding but also fragmenting margin.", instruments: "Novo Nordisk, Eli Lilly, Veeva Systems, McKesson, GE HealthCare",
      highlights: [
        { name: "Novo Nordisk", change: "-3.2%", note: "Wegovy maintains 65% of US new prescriptions but Foundayo oral competition directly attacks its primary market; guiding 2026 revenue and profit decline as pricing pressure and competition intensify." },
        { name: "Veeva Systems", change: "+1.2%", note: "Life sciences CRM [customer relationship management] and data platform benefiting from GLP-1 commercial launches requiring intensive data infrastructure; both Novo and Lilly are major Veeva clients expanding their commercial tech spending." },
        { name: "McKesson", change: "+0.9%", note: "Drug distribution backbone for GLP-1 category — as market expands with oral formats, McKesson's distribution economics improve regardless of which manufacturer wins market share." },
        { name: "GE HealthCare", change: "+0.7%", note: "Imaging and diagnostics demand rising as GLP-1 patients require more frequent metabolic and cardiovascular monitoring; an adjacency play on the obesity treatment ecosystem." }
      ]
    },
    { num: "05", title: "Trade Fragmentation Creating Shipping Opportunities", status: "WEAKENED", evidence: "Iran-US ceasefire talks reducing tanker risk premium; container charter rates soft from newbuild oversupply — both major shipping sub-sectors headwinded simultaneously this week.", instruments: "Global Ship Lease, International Seaways, Danaos, Tsakos Energy Navigation, StealthGas",
      highlights: [
        { name: "Global Ship Lease", change: "+0.7%", note: "100% 2026 charter coverage and 86% for 2027 with $2.05B total contracted revenue insulates from spot rate weakness; Zim Norfolk and Zim Xiamen 60-63 month extensions locked at strong rates." },
        { name: "International Seaways", change: "-5.5%", note: "Tanker-specific geopolitical premium unwinding as Iran-Hormuz peace deal approaches; crude routing from Middle East potentially normalising reduces voyage economics materially." },
        { name: "Danaos", change: "-3.9%", note: "Container oversupply from 2021-2023 newbuild cycle hitting charter renewal rates; spot rates approaching cash break-even for smaller operators; long-term contracts masking near-term stress." },
        { name: "StealthGas", change: "-4.2%", note: "LPG [liquefied petroleum gas] charter rates softening; smaller fleet operators lack pricing power in surplus environment; geopolitical premium unwinding from energy-adjacent shipping." }
      ]
    },
    { num: "06", title: "Retail Cash Rotation to Equities Building", status: "CONFIRMED", evidence: "S&P 500 posted its eighth consecutive weekly gain — longest streak since 2023 — with retail participation at ~20% of average daily volume; JPMorgan data shows retail inflows +60% YoY.", instruments: "Vanguard S&P 500, SPDR Russell 2000, iShares Core S&P 500, Robinhood, Interactive Brokers",
      highlights: [
        { name: "Robinhood", change: "+1.5%", note: "Retail trading platform directly benefiting from surge in individual investor participation; options volume from retail reaching 50% of total on peak days; retail equity allocation rising structurally." },
        { name: "Interactive Brokers", change: "+1.2%", note: "Higher trading volumes and elevated interest rates on cash balances supporting revenue; institutional and sophisticated retail segments both growing as market hits 8-week winning streak." },
        { name: "Vanguard S&P 500 ETF", change: "+0.9%", note: "Eighth consecutive weekly inflow; passive allocation trend continues as retail investors systematically deploy savings into index funds alongside active individual stock picks." },
        { name: "SPDR Russell 2000", change: "+0.6%", note: "Small-cap breadth improving as the rally broadens beyond Mag7 — Russell 2000 participation signals the equity rotation thesis is moving beyond large-cap tech concentration." }
      ]
    }
  ],

  discoveries: [
    { num: "01", company: "TJX Companies", sector: "Consumer Retail", headline: "TJX Q1 FY2027: Revenue $14.32B and EPS $1.19 both beat consensus; full-year guidance raised — largest weekly gain in the consumer sector at +9.2%", detail: "TJX's blowout quarter confirmed that the off-price retail model is one of the primary beneficiaries of persistent consumer inflation stress. When shoppers can no longer afford full-price department stores, TJX Maxx, HomeGoods, and Marshalls capture the trade-down volume at structurally higher margins than the stores losing the traffic. The +9.2% weekly move validated the thesis that value retail is not just a defensive play — it is an offensive growth story in the current macro regime. This matters for understanding the consumer health divergence: low-end consumers are stressed but still spending, just at different addresses.", tag: "BULL" },
    { num: "02", company: "Nvidia / TSMC", sector: "Semiconductors", headline: "Jensen Huang flew to TSMC to lock Vera Rubin production commitments — Computex 2026 GTC Taipei keynote announced for June 1", detail: "The physical act of Nvidia's CEO travelling to TSMC's headquarters to personally secure production commitments signals that Vera Rubin supply is the single most strategically important variable in 2026 for Nvidia's revenue trajectory. The keynote on June 1 is set to define AI infrastructure investment decisions for the following 12-18 months. A CEO-level site visit to a supplier is a rare event and almost always precedes a major commercial announcement — watch this carefully for implications across the entire AI supply chain from TSMC to SK Hynix to Broadcom.", tag: "BULL" },
    { num: "03", company: "MercadoLibre", sector: "EM / Latin America Tech", headline: "Q1 2026 revenue +49% YoY to $8.85B but net income fell 16% — stock down 14% in one week", detail: "MercadoLibre's paradox — explosive top-line growth at 49% while net income falls 16% — illustrates the profitability challenge of scaling fintech in high-inflation LatAm markets where credit loss provisions are rising faster than fee income. The 14% weekly decline is a reminder that high-growth EM companies can disappoint on the metric that ultimately matters to institutional holders. The stock is now down 39% over the past year despite the underlying business growing at extraordinary speed, creating a genuine valuation argument only for investors who can tolerate EM credit cycle volatility.", tag: "WATCH" },
    { num: "04", company: "SMIC / China", sector: "Semiconductors", headline: "SMIC testing first domestic immersion DUV lithography machine — potential path to 7nm via multipatterning without ASML equipment", detail: "China's SMIC is now physically testing a domestic immersion DUV [deep ultraviolet lithography — a key manufacturing step to make sub-28nm chips] machine from Yuliangsheng, reportedly capable of 28nm-class production that could be extended to 7nm via multipatterning [stacking multiple exposures to achieve smaller features at the cost of more production steps]. If confirmed at volume, this is the first credible step toward Chinese lithography self-sufficiency. It does not immediately threaten ASML's EUV monopoly, but it signals that China is closer to breaking its 28nm ceiling than the market currently prices — upgrading the ASML geopolitical moat risk from theoretical to physical.", tag: "BEAR" },
    { num: "05", company: "Kevin Warsh / Federal Reserve", sector: "Monetary Policy", headline: "Kevin Warsh sworn in as new Fed chair — most divisive confirmation in Fed history at 54-45 — inherits core PCE at 3.2%", detail: "Warsh's confirmation in a 54-45 Senate vote signals that monetary policy is now overtly political. He inherits core PCE [the Fed's inflation measure] at 3.2% and rising, shelter inflation doubling in April, and oil only just below $100. Markets price zero rate cuts in 2026, and some desks are raising September hike odds above 5%. The structural implication: any equity multiple expansion must come from earnings growth alone, not from rate-cut-driven discount rate compression — fundamentally shifting the risk/reward equation for high-multiple tech names over the second half.", tag: "BEAR" },
    { num: "06", company: "Google / Anthropic", sector: "AI / Cloud", headline: "Google deployed over 1 million Ironwood TPU chips for Anthropic inference workloads — largest single ASIC deployment in history", detail: "Google's deployment of more than one million Ironwood TPU v7 chips for Anthropic represents the first ASIC [custom-designed chip] to reach seven-figure deployment volume at a single customer. This is a pivotal data point for the NVIDIA TAM [total addressable market — the total universe of revenue available] debate — if Anthropic, the leading frontier AI lab, is running meaningful inference workloads on Google TPU rather than NVIDIA GPUs, the custom silicon thesis has moved from potential risk to confirmed demand. NVIDIA's training revenue appears safe for now, but inference — the faster-growing, higher-volume segment — is clearly contested terrain.", tag: "WATCH" },
    { num: "07", company: "Micron", sector: "Memory Semiconductors", headline: "Micron began mass production of HBM4 for Nvidia Vera Rubin — but SemiAnalysis estimates SK Hynix gets 70% and Samsung 30% of first-wave orders, leaving Micron at zero", detail: "Micron's HBM4 production start is a milestone, but SemiAnalysis's estimate that NVIDIA allocated 70% of Vera Rubin HBM to SK Hynix and 30% to Samsung — with zero to Micron in the first wave — is a significant setback for Micron bulls. Micron has its 2026 HBM supply fully booked but appears to be selling to customers other than NVIDIA for the Vera Rubin platform. SK Hynix's dominant 62% overall HBM market share is now further entrenched by the Vera Rubin allocation. This is a rotation signal within memory, not a sector exit — SK Hynix is the cleaner HBM play while Micron's Vera Rubin exclusion resolves in future product cycles.", tag: "WATCH" },
    { num: "08", company: "Berkshire Hathaway / Greg Abel", sector: "Financials / Conglomerate", headline: "Greg Abel's first 13F as Berkshire CEO: exited Visa, Mastercard, Amazon, UnitedHealth — tripled Google bet, added $2.65B in Delta Air Lines", detail: "Greg Abel's debut portfolio disclosure reveals a significant philosophical shift from Warren Buffett's final quarter. Abel eliminated Todd Combs-managed positions (Visa, Mastercard) and made large directional bets: tripling Berkshire's Alphabet stake signals conviction in the cloud and AI revenue story, while the $2.65B Delta initiation signals Abel sees air travel as undervalued relative to the strong travel recovery narrative. The Berkshire portfolio resizing from 40 to 26 positions reflects Abel's preference for concentration. Following this signal more closely could provide an edge — Berkshire's position changes have historically led institutional consensus by 2-3 quarters.", tag: "BULL" }
  ],

  risers: [],

  ai_trade: {
    status: "INTACT",
    indicators: [
      {
        id: "capex_language",
        label: "Hyperscaler CapEx Language",
        info: "Forward-looking capex statements from Meta, Microsoft, Google, Amazon. Commitments are made 12-18 months before they appear in earnings — a hedge phrase is the earliest warning of demand softening. AMBER means semi names face margin compression risk within 2 quarters.",
        signal: "GREEN",
        finding: "All four hyperscalers reaffirmed or raised 2026 capex guidance in Q1 earnings: Meta to $145B, Microsoft to $190B, Alphabet to $190B, Amazon to $200B+ — a combined $725B+ commitment for AI infrastructure. No hedging language detected; Zuckerberg's only caveat was calling ROI questions very technical rather than signalling demand concern.",
        implication: "Semiconductor and infrastructure names (TSMC, Broadcom, SK Hynix) have revenue visibility through at least 2027; this is the strongest possible GREEN signal for sustained AI spending."
      },
      {
        id: "hbm_pricing",
        label: "HBM / DRAM Spot Pricing",
        info: "HBM [high-bandwidth memory] and DRAM spot prices lead semiconductor earnings by 6-8 weeks. A price plateau precedes margin guidance cuts by two earnings cycles.",
        signal: "GREEN",
        finding: "Samsung and SK Hynix reportedly implementing ~20% HBM3E price hike for 2026 as NVIDIA H200 and ASIC demand rises. Goldman Sachs raised its 2026 DRAM supply-demand gap forecast from 3.3% to 4.9%, calling it the most severe shortage in 15 years. SK Hynix Q1 FY2026 operating margin hit 72%.",
        implication: "HBM pricing power intact and accelerating — SK Hynix and Samsung are structurally positioned to expand margins through 2026-2027; no early warning signals of demand softening visible in pricing data."
      },
      {
        id: "capex_revenue_gap",
        label: "CapEx-to-Revenue Gap",
        info: "The bubble signal: if hyperscalers spend $200B+ on AI infrastructure but cannot show proportional AI-attributable revenue growth, the trade is pricing future potential not current cash flows.",
        signal: "AMBER",
        finding: "Microsoft Azure AI annualised at $37B (+123%) and Google Cloud at $80B+ run rate (+63%) show revenue catching up — but Meta raised capex to $145B and when asked about AI ROI, Zuckerberg called it a very technical question. Combined hyperscaler capex now at $725B+ while AI-attributable revenue across all four is still well below $200B annualised.",
        implication: "Gap is narrowing but not yet closed — Microsoft is the most credible with explicit AI revenue disclosures; Meta's capex without transparent AI revenue attribution is the primary AMBER signal. Not yet a RED but bears watching into Q2 earnings season."
      },
      {
        id: "multiple_expansion",
        label: "Mag7 Multiple Expansion vs. EPS Revisions",
        info: "P/E [price-to-earnings] expansion on rising earnings = fundamentals. On flat or declining earnings = pure sentiment. These look identical on price charts.",
        signal: "GREEN",
        finding: "Nvidia forward P/E at ~24x on $91B Q2 guide — multiple is stable or compressing while earnings estimates rise sharply. Alphabet at ~22x forward earnings with Cloud accelerating. Apple at 31x with EPS growing 22%. Across the Mag7, EPS revisions are directionally up, supporting the view that multiple expansion is fundamentally driven.",
        implication: "P/E expansion on rising earnings is the healthy form of market appreciation — fundamentals are driving the AI trade, not pure sentiment. This GREEN signal is the most important indicator of AI trade structural health."
      },
      {
        id: "china_chips",
        label: "China Chip Progress (SMIC / Huawei)",
        info: "ASML, NVIDIA, TSMC carry geopolitical monopoly premiums. A credible Chinese alternative at advanced nodes compresses these premiums immediately.",
        signal: "AMBER",
        finding: "SMIC is now physically testing a domestic immersion DUV [deep ultraviolet lithography] machine from Yuliangsheng, capable of 28nm-class production with multipatterning potential toward 7nm. China's top chip executives simultaneously issued a public call for national consolidation of lithography efforts, admitting current capability is small, fragmented, and weak — but the SMIC DUV hardware test is the first credible physical step beyond pure advocacy.",
        implication: "ASML's EUV monopoly is structurally safe for 3-5 years but the 28nm-to-7nm domestic DUV path is now a physical rather than theoretical risk; ASML geopolitical premium faces gradual compression over the medium term — not immediate but no longer zero probability."
      }
    ]
  },

  semis: {
    status: "WATCH",
    regions: [
      {
        region: "Korea",
        info: "Korea supplies ~95% of global HBM [high-bandwidth memory]. Production disruption propagates to NVIDIA allocation within 4-6 weeks. Samsung strike losing share to SK Hynix = rotation within sector, not a sector exit.",
        signal: "GREEN",
        finding: "SK Hynix maintains 62% HBM market share with Q1 FY2026 operating margin at 72% and revenue up 198% YoY. Samsung racing to qualify HBM4 for Nvidia Vera Rubin but per SemiAnalysis estimates is allocated only 30% of first-wave Vera Rubin HBM. Both Samsung and SK Hynix are scaling capacity 20-50% in 2026. No labor disruptions reported this week.",
        implication: "Stable supply with SK Hynix dominant — within-sector rotation favours SK Hynix over Samsung for Vera Rubin exposure; Micron locked out of first wave creates a near-term headwind for Micron's HBM thesis."
      },
      {
        region: "Japan",
        info: "Two levers: (1) TSMC Kumamoto new capacity affects global supply/demand; (2) BOJ rate hike unwinds the JPY carry trade [cheap yen borrowed to buy global assets], hitting tech stocks within hours via forced position unwinding.",
        signal: "AMBER",
        finding: "BOJ held at 0.75% in April but raised inflation forecast to 2.8% from 1.9% citing Iran-related energy costs; the April summary of opinions flagged a possible June rate hike. TSMC Kumamoto confirmed upgrade from 7nm to 3nm with Sony Semiconductor joint venture announced May 27 for a new Koshi City fab.",
        implication: "TSMC Kumamoto upgrade is structurally positive for Japan semiconductor sovereignty; BOJ June hike risk is the primary near-term threat — a surprise hike would unwind JPY carry positions and hit Tokyo Electron, Renesas, and global tech multiples within hours."
      },
      {
        region: "China / Taiwan",
        info: "Two risks: (1) TSMC CoWoS [advanced chip packaging] capacity is the direct NVIDIA GPU output bottleneck; (2) China rare earth export controls are deployable without military escalation.",
        signal: "AMBER",
        finding: "TSMC CoWoS is sold out through 2026; Jensen Huang's personal visit this week to lock Vera Rubin supply commitments indicates the bottleneck is the tightest it has ever been. SMIC DUV machine test represents a modest step toward Chinese domestic capability. Taiwan political signals remain stable. No rare earth disruption this week but China-US trade negotiations ongoing.",
        implication: "CoWoS bottleneck limits Nvidia GPU output even with infinite demand — TSMC's packaging capacity is the single most valuable industrial asset in AI infrastructure. SMIC DUV progress is an AMBER flag deserving quarterly monitoring."
      },
      {
        region: "USA",
        info: "US policy sets global semiconductor rules. Export control expansions cut off demand or supply overnight. The CHIPS Act [$52B subsidy programme] drives 5-10 year capex decisions for TSMC Arizona, Intel, and Samsung US fabs.",
        signal: "GREEN",
        finding: "BIS revised January 2026 export controls to case-by-case review for H200-class chips to China (easing from blanket denial). White House implemented 25% tariff on semiconductor imports under Section 232. TSMC Arizona fabs on track; Intel restructuring under Lip-Bu Tan continuing. CHIPS Act disbursements proceeding without major dispute this week.",
        implication: "Policy environment stable with export controls slightly eased for H200-class chips — positive for Nvidia's addressable market; semiconductor import tariff adds cost pressure for non-US foundries serving the US market."
      }
    ],
    moat_watch: [
      {
        incumbent: "ASML",
        challenger: "SMEE / China",
        domain: "EUV / DUV Lithography Equipment",
        info: "ASML monopolises EUV [extreme ultraviolet lithography]. SMEE is China's domestic alternative, currently at ~28nm. Advancement compresses the geopolitical premium in ASML's valuation.",
        signal: "AMBER",
        finding: "SMIC is testing a domestic immersion DUV machine from Yuliangsheng designed for 28nm-class production but capable of multipatterning toward 7nm. China's top chip executives publicly admitted their domestic lithography capability is small, fragmented, and weak while calling for national consolidation. SiCarrier announced ASML-compatible tool roadmap with 2026 targets.",
        implication: "ASML's EUV monopoly is safe for 3-5 years but the 7nm-via-multipatterning DUV path is now a physical rather than theoretical risk — upgrade the China chip watch from GREEN to AMBER and reassess quarterly for yield reports."
      },
      {
        incumbent: "SK Hynix / Samsung",
        challenger: "Micron",
        domain: "HBM Memory Market Share",
        info: "Micron is the third HBM entrant. Share gains compress SK Hynix/Samsung pricing power. If Samsung loses share due to strike/yield issues, SK Hynix and Micron are the rotation beneficiaries.",
        signal: "GREEN",
        finding: "SK Hynix + Samsung holding combined ~80% HBM market share. SemiAnalysis estimates Nvidia allocated SK Hynix 70% and Samsung 30% of Vera Rubin HBM orders with Micron receiving zero in first wave. Micron has HBM4 supply fully booked but selling to non-Nvidia customers. SK Hynix continues to dominate the highest-value NVIDIA allocation slot.",
        implication: "SK Hynix / Samsung moat is intact and reinforced by Vera Rubin allocation data; Micron is a long-term challenger but the first-wave exclusion is a near-term headwind for its HBM thesis specific to NVIDIA product cycles."
      },
      {
        incumbent: "NVIDIA",
        challenger: "Hyperscaler Custom Silicon",
        domain: "AI Training Chips (Google TPU / AWS Trainium / Microsoft Maia)",
        info: "Custom silicon erodes NVIDIA's TAM [total addressable market] from within. A 20%+ training workload shift reprices NVIDIA's growth ceiling embedded in its 35x forward P/E.",
        signal: "AMBER",
        finding: "Google deployed 1M+ Ironwood TPU v7 chips for Anthropic inference workloads — the largest single ASIC deployment at any customer ever. Microsoft Maia 200 claims 3x FP4 performance vs AWS Trainium3. Custom ASICs growing at 44.6% CAGR targeting inference (two-thirds of all AI compute). Inference workloads are clearly shifting to custom silicon; training remains NVIDIA-dominated.",
        implication: "NVIDIA's training monopoly appears safe through the Vera Rubin cycle; inference erosion by custom silicon is real and accelerating but training — the higher-margin, higher-unit-value segment — is the key battleground and still NVIDIA's to lose."
      },
      {
        incumbent: "TSMC CoWoS",
        challenger: "Samsung / Amkor / ASE",
        domain: "Advanced AI Chip Packaging",
        info: "CoWoS [Chip-on-Wafer-on-Substrate] is the current GPU production bottleneck. Alternatives relieve the AI chip crunch but reduce TSMC's packaging pricing power.",
        signal: "GREEN",
        finding: "TSMC CoWoS is sold out through 2026 with scaling from 35,000 to 130,000 wafers/month underway. TSMC has outsourced simpler packaging steps to ASE and Amkor to expand throughput but CoWoS advanced steps remain TSMC-only. Samsung and Intel EMIB are being evaluated as alternatives but neither has achieved equivalent yield at the volume required by Nvidia.",
        implication: "TSMC CoWoS moat is fully intact through 2026; any Samsung or Amkor qualification at equivalent yield would be a multi-year positive for hyperscalers (lower GPU cost) and a negative for TSMC packaging pricing power — watch for yield reports from these challengers in H2 2026."
      }
    ]
  }

};
